// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smshdpbqaqshlkuunzor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtc2hkcGJxYXFzaGxrdXVuem9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTQ2ODQsImV4cCI6MjA1OTE3MDY4NH0.XxUyRT651V0xo0MSUN6F-4ADTqrY7PIO_nc_J0hXVbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);